### ISSUE TITLE
How long to sync?

### ISSUE THREAD

**Issue by ntillet** [MysticRyuujin/dappnode-polygon#1]
I've left it for over 2 days and got like 2 months left to sync.
Note that I've got a download error in the middle at around 40% and it restarted.

Is there any way to load up a snapshot or similar?

**Comment by MysticRyuujin** [comment]
There is a snapshot function. Maybe we can convince @androolloyd to add instructions to the README? I'm not sure how it's done in the dappnode config.

**Comment by eniolasonowo** [comment]
Right now, syncing bor is now work since polygon TPS has doubled.
I will advice to use a larger instance.
