### ISSUE TITLE
dappnode package

### ISSUE THREAD

**Issue by GPConnect** [MysticRyuujin/dappnode-polygon#2]
why it do not appear here so i can simply add it to dappnode ?
https://dappnode.github.io/explorer/#/

**Comment by MysticRyuujin** [comment]
I'm not sure how to get this as an official package. Maybe someone over there can point us in the right direction? @androolloyd is my dappnode guru

**Comment by androolloyd** [comment]
We can release it this weekend.

**Comment by androolloyd** [comment]
https://dappnode.github.io/explorer/#/repo/0x1148e67dcbd11b63bd53e45dc4a9565c0ad66a7c
