### ISSUE TITLE
Figuring out ports, domains and volumes used by docker-compose

### ISSUE THREAD

**Issue by miohtama** [MysticRyuujin/dappnode-polygon#4]
I am looking the [docker-compose file](https://github.com/MysticRyuujin/dappnode-polygon/blob/main/docker-compose.yml)

I am trying to figure out the host and port configuration of the default docker-compose providers.

* What ports and hostnames are used
* Why are they used
* Which ports should be public 
* Which ports are dangerous and definitely should not be public (RPC?, RabbitMQ)
* What volumes there are to map, so I can map them to the host file system for the persistency

**Comment by MysticRyuujin** [comment]
Yeah, I don't think the rabbitmq port "5672" needs to be exposed at all. That's internal only. And there was a discussion on Twitter today suggesting we don't even need the rabbitmq server :man_shrugging: 

The heimdalld ports of 26656 and 26657 are for peering of their PoS nodes, so they have to be exposed if you want to allow incoming peer connections.

The heimdallr port of 1317 probably doesn't need to be exposed, unless you want to be able to query it, it's mostly just for the bor -> heimdallr connection. I've not found another use for it.

Finally, the bor ports 8545 and 8546 are for JSON-RPC and WebSocket and 30303 is for peering

Exposing the JSON-RPC/WebSocket externally (i.e. The Internet) is not recommended but there's no other way to talk to it outside of the docker environment if it's not exposed.

**Comment by GPConnect** [comment]
in other words, open p2p port 26656 for node to node communication and connect your wallet tp rpc port 26657 using a vpn ! 
ps: The package for dappnode can't be installed ! the image is not found !
