### ISSUE TITLE
bor doesn't receive SIGINT/TERM at docker-compose stop/down

### ISSUE THREAD

**Issue by memoverflo** [MysticRyuujin/dappnode-polygon#7]
should use `exec ...` to start the last command in entrypoint.sh?

**Comment by MysticRyuujin** [comment]
I think I get what you're saying, but to confirm:

Modify `sh -c` to be `exec`?

If I'm reading here correctly, I think that's all we need to do?

https://hynek.me/articles/docker-signals/

@androolloyd thoughts?
